version: '3.8'

services:
    web:
        build: .
        # command: python /timeofyourlife_v1/manage.py runserver 0.0.0.0:8000
        command: gunicorn timeofyourlife_v1.wsgi -b 0.0.0.0:8000
        volumes:
            - .:/timeofyourlife_v1
        ports:
            - 8000:8000
            - 35729:35729
        depends_on:
            - db
            - selenium
        environment:
            - 'DJANGO_DEBUG=True'
            - 'DJANGO_SECURE_SSL_REDIRECT=False'
            - 'DJANGO_SECURE_HSTS_SECONDS=0'
            - 'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False'
            - 'DJANGO_SECURE_HSTS_PRELOAD=False'
            - 'DJANGO_SESSION_COOKIE_SECURE=False'
            - 'DJANGO_CSRF_COOKIE_SECURE=False'
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - 'POSTGRES_HOST_AUTH_METHOD=trust'
    selenium:
        image: selenium/standalone-firefox
        ports: 
            - 4444:4444

volumes:
    postgres_data: