version: "3.8"

services:
  web:
    build: .
    restart: always
    volumes:
      - static_prod:/vol/web/static_prod
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - MY_EMAIL_HOST=${MY_EMAIL_HOST}
      - MY_EMAIL_HOST_PASSWORD=${MY_EMAIL_HOST_PASSWORD}
      - MY_EMAIL_HOST_USER=${MY_EMAIL_HOST_USER}
      - MY_EMAIL_PORT=${MY_EMAIL_PORT}
      - GMAIL=${GMAIL}
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_PORT=${DB_PORT}"
  db:
    image: postgres:13
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - ${DB_PORT}:5432
  proxy:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - web
    ports:
      - ${PROXY_PORT}:8000
    volumes:
      - static_prod:/vol/static_prod

volumes:
  postgres_data:
  static_prod:
