# Generated by Django 3.2.5 on 2021-07-25 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('event_name', 'event_date', 'owner')},
        ),
    ]
