# Generated by Django 3.2.5 on 2021-08-02 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_alter_userevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='day',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevent',
            name='month',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevent',
            name='year',
            field=models.PositiveIntegerField(default=2001, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2999)]),
            preserve_default=False,
        ),
    ]
