# Generated by Django 3.2.5 on 2021-07-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_feedback_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
    ]
