# Generated by Django 3.2.5 on 2021-08-01 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='month',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.PositiveIntegerField(default=1995, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2999)]),
            preserve_default=False,
        ),
    ]
